### ISSUE TITLE
Unicode-Escape-Sequence

### ISSUE THREAD

**Issue by H1ghBre4k3r** [OsamaAbbas/enpaki#1]
Hey,
when i try to compile a .js-file with your bytenode-compiler, which got bundled with enpaki, i get this error (on windows). On MacOS, everything works fine. 

![image](https://user-images.githubusercontent.com/32372790/61177299-2ee53800-a5d2-11e9-9d47-b8442b220f27.png)

Steps to reproduce:
* use windows
* bundle a file
* try to compile it

**Comment by H1ghBre4k3r** [comment]
I kinda figured it out myself - it has something to do with the windows filesystem. If you change `readFile`, it should work:
```javascript
readFile(filename) {
        let code = this.compile(filename);
        let moduleIdentity =
            process.platform == "darwin"
                ? this.moduleIdentity(filename)
                : this.moduleIdentity(filename)
                      .split("\\")
                      .join("/");

        code = code
            .replace(/^#!.*/, "")
            .replace(this.REGEX_REQUIRE, (match, moduleName) => this.requireModule(match, moduleName, filename));

        this.parsedFiles.push(filename);
        return FILE_HEADER(moduleIdentity) + code + FILE_FOOTER(moduleIdentity);
    }
```

**Comment by OsamaAbbas** [comment]
This bus is due to the use of `\` in Windows system. Your fix is fine, but it should test for "windows" not "darwin", because we want "linux" to behave like "darwin".

If you wish, please open a pull request and I will accept and publish the fix in npm. Thank you.
